### ISSUE TITLE
Where do you place the DRM files ?

### ISSUE THREAD

**Issue by Crestil** [sim0n00ps/OF-DRM#12]
I renamed the files to device_client_id_blob and device_private_key but I keep getting the following error:

Exception caught: The type initializer for 'WidevineClient.Widevine.CDM' threw an exception.

StackTrace:    at WidevineClient.Widevine.CDM.OpenSession(String initDataB64, String deviceName, Boolean offline, Boolean raw)
   at WidevineClient.Widevine.CDMApi.GetChallenge(String initDataB64, String certDataB64, Boolean offline, Boolean raw)
   at OF_DRM_Video_Downloader.Helpers.APIHelper.GetDecryptionKeyNew(Dictionary`2 drmHeaders, String licenceURL, String pssh)

Inner Exception:
Exception caught: No client id blob found

StackTrace:    at WidevineClient.Widevine.CDMDevice..ctor(String deviceName, Byte[] clientIdBlobBytes, Byte[] privateKey

**Comment by Crestil** [comment]
Nvm, I saw in the instruction it says to place them in the cdm folder.
