### ISSUE TITLE
 No client id blob found, but files present

### ISSUE THREAD

**Issue by Doesntmatter430** [sim0n00ps/OF-DRM#18]
I followed the guide to get the `device_client_id_blob` and `device_private_key` files which are in the cdm folder

C:\Users\dm\Downloads\OF.DRM.V1.7\cdm\devices\chrome_1610\device_client_id_blob.bin
C:\Users\dm\Downloads\OF.DRM.V1.7\cdm\devices\chrome_1610\device_private_key.pem

auth is set up and able to log me in fine. When i go to download posts, it only shows 9 posts out of many, and when i try to download any i get this error and then files download as separate mp4 and m4a files which i cant get to play.

```
Downloading 1 Video(s) ----------------------------------------   0% 0.0/33.4 MB --:--:--
        Exception caught: The type initializer for 'WidevineClient.Widevine.CDM' threw an exception.

StackTrace:    at WidevineClient.Widevine.CDM.OpenSession(String initDataB64, String deviceName, Boolean offline, Boolean raw)
   at WidevineClient.Widevine.CDMApi.GetChallenge(String initDataB64, String certDataB64, Boolean offline, Boolean raw)
   at OF_DRM_Video_Downloader.Helpers.APIHelper.GetDecryptionKeyNew(Dictionary`2 drmHeaders, String licenceURL, String pssh)

Inner Exception:
Exception caught: No client id blob found

StackTrace:    at WidevineClient.Widevine.CDMDevice..ctor(String deviceName, Byte[] clientIdBlobBytes, Byte[] privateKey
Downloading 1 Video(s) ----------------------------------------   0% 0.0/33.4 MB --:--:--
        Exception caught: Could not find file 'C:\Users\dm\Downloads\OF.DRM.V1.7\__user_data__\sites\OnlyFans\nnnnekochan\Posts\Free\Videos\0hk08umn664sai9tupibv_source.mp4'.

StackTrace:    at System.IO.FileSystem.OpenHandleToWriteAttributes(String fullPath, Boolean asDirectory)
   at System.IO.FileSystem.SetFileTime(String fullPath, Boolean asDirectory, Int64 creationTime, Int64 lastAccessTime, Int64 lastWriteTime, Int64 changeTime, UInt32 fileAttributes)
   at System.IO.FileSystem.SetLastWriteTime(String fullPath, DateTimeOffset time, Boolean asDirectory)
   at System.IO.File.SetLastWriteTime(String path, DateTime lastWriteTime)
   at OF_DRM_Video_Downloader.Helpers.DownloadHelper.DownloadPostDRMVideo(String ytdlppath, String mp4decryptpath, Strin                                                                                     , String url, String decryption
Downloading 1 Video(s) ----------------------------------------   0% 0.0/33.4 MB --:--:--
```

**Comment by FeelsGouda** [comment]
Not sure if still relevant, but in case others have the same question: Remove the endings of the files.

need to remove the ".bin" and ".pem" from the files when you rename and copy them over.
