### ISSUE TITLE
Problem getting DRM keys

### ISSUE THREAD

**Issue by jretro4** [sim0n00ps/OF-DRM#5]
I followed the instructions of Dumping Your onw L3 CDM, everything loads perfectly but the problem is that it is only for previous versions of Android 11, in the tutorial it does it from android 9 and onlyfans does not load in that version, it keeps loading the onlyfans logo without entering the page. I tried it with later versions but the program to obtain the keys fails, in the android 11 version it does not generate the keys but it does not give an error either, could you tell me exactly how you do it to generate the keys please? I swear I'll make it up to you

**Comment by jretro4** [comment]
I'll try it right now and let you know

**Comment by jretro4** [comment]
After generating the keys exactly as the videohelp forum tutorial said, I sent the two files to the chrome_1610 folder and renamed it to device_client_id_blob.bin and device_private_key.pem

I then ran OF-DL.exe and it returned the following after detecting a drm video:

Exception caught: The type initializer for 'WidevineClient.Widevine.CDM' threw an exception.                                                                                                                                                                                                                                                                                                                                                                  StackTrace:    
at WidevineClient.Widevine.CDM.OpenSession(String initDataB64, String deviceName, Boolean offline, Boolean raw) at WidevineClient.Widevine.CDMApi.GetChallenge(String initDataB64, String certDataB64, Boolean offline, Boolean raw) 
at OF_DL.Helpers.APIHelper.GetDecryptionKeyNew(Dictionary`2 drmHeaders, String licenceURL, String pssh, Auth auth)                                                                                                                                                                                                                                                                                                                                                                     Inner Exception: 
Exception caught: No client id blob found

and this:

Exception caught: Could not find file
 
'C:\Users\User\Desktop\OFDL\OF.DL.V1.7.23\__user_data__\sites\OnlyFans\userof\Messages\Free\Videos\0hr2gu93urhki6kvbhe2z_source.mp4'.

StackTrace:
   at System.IO.FileSystem.OpenHandleToWriteAttributes(String fullPath, Boolean asDirectory)
   at System.IO.FileSystem.SetFileTime(String fullPath, Boolean asDirectory, Int64 creationTime, Int64 lastAccessTime, Int64 lastWriteTime, Int64 changeTime, UInt32 fileAttributes)
   at System.IO.FileSystem.SetLastWriteTime(String fullPath, DateTimeOffset time, Boolean asDirectory)
   at System.IO.File.SetLastWriteTime(String path, DateTime lastWriteTime)
   yptpath, String ffmpegpath, String user_agent, String policy, String signature, String kvp, String sess, String url, String 
   decryptionKey, String
   
   I've been trying for a long time and finally I need to ask for help. What I can do? I will pay your help

**Comment by sim0n00ps** [comment]
Remove the file extensions from the device_client_id_blob.bin and device_private_key.pem files so they become device_client_id_blob and device_private_key

**Comment by thegitdanger** [comment]
Bros! I'm making a telegram group about Onlyfans DRM, would you like to come?
https://t.me/onlydrm
